### ISSUE TITLE
iOS版クライアントの作成

### ISSUE THREAD

**Issue by mitsugogo** [hamache9821/ImacocoServer#5]
さて誰かいないもんか

**Comment by hamache9821** [comment]
誰か作って
もしくは、現状ある接続先を変更できる機能を付けてください
※ここはサーバのリポだからクライアントんの話題は少々スレ違いではある

**Comment by hamache9821** [comment]
[@kazusap](https://twitter.com/kazusap) が[重い腰](https://twitter.com/kazusap/status/785354493592412160)を上げてくれたのでなんとかなりそう

**Comment by hamache9821** [comment]
guaa.nyabu.in
